export const GET_TOTAL_COUNT_BOTH = "DashboardState/GET_TOTAL_COUNT_BOTH"
export const GET_TOTAL_COUNT_BOTH_FULFILLED = "DashboardState/GET_TOTAL_COUNT_BOTH_FULFILLED"
export const GET_USER_IMPROVEMENT_CHART = "DashboardState/GET_USER_IMPROVEMENT_CHART"
export const GET_USER_IMPROVEMENT_CHART_FULFILLED = "DashboardState/GET_USER_IMPROVEMENT_CHART_FULFILLED"

export const GET_RIDE_COLLISION_FULFILLED = "DashboardState/GET_RIDE_COLLISION_FULFILLED"
export const GET_RIDE_COLLISION = "DashboardState/GET_RIDE_COLLISION"